# Generated by Django X.X.X on 2024-XX-XX
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(unique=True, max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('dosen', 'Dosen'), ('mahasiswa', 'Mahasiswa')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(unique=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='admin_web.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(unique=True, max_length=254)),
                ('nip', models.CharField(max_length=255, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosen', to='admin_web.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(unique=True, max_length=254)),
                ('nim', models.CharField(max_length=255, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('is_wajah_exist', models.BooleanField(default=False)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('nik', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='admin_web.User')),
            ],
            options={
                'abstract': False,
            },
        ),
                migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruang', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nama_english', models.CharField(blank=True, max_length=255, null=True)),
                ('kode', models.CharField(max_length=255, unique=True)),
                ('tipe', models.CharField(max_length=255)),
                ('sks', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=255)),
                ('kode_kelas', models.CharField(max_length=255, unique=True)),
                ('hari', models.CharField(max_length=255)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('kapasitas', models.IntegerField()),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='admin_web.MataKuliah')),
                ('ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='admin_web.Ruang')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('status', models.CharField(max_length=255)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kelas', to='admin_web.MataKuliah')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kelas', to='admin_web.Kelas')),
                ('ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kelas', to='admin_web.Ruang')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kelas', to='admin_web.Dosen')),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliahDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.MataKuliah')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.Dosen')),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliahMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_mengambil', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.MataKuliah')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.Mahasiswa')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.Kelas')),
            ],
        ),
        migrations.CreateModel(
            name='PresensiMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('alpha', 'Alpha'), ('izin', 'Izin'), ('sakit', 'Sakit')], blank=True, max_length=100, null=True)),
                ('presensi_oleh', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_presensi', models.DateField(blank=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.Mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.MataKuliah')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.Kelas')),
                ('jadwal_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='admin_web.JadwalKelas')),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='mata_kuliah',
            field=models.ManyToManyField(through='admin_web.MataKuliahMahasiswa', related_name='mahasiswas', to='admin_web.MataKuliah'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='kelas',
            field=models.ManyToManyField(through='admin_web.MataKuliahMahasiswa', related_name='mahasiswas', to='admin_web.Kelas'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='jadwal',
            field=models.ManyToManyField(through='admin_web.PresensiMahasiswa', related_name='mahasiswas', to='admin_web.JadwalKelas'),
        ),
    ]
