# Generated by Django 5.1.1 on 2024-10-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MataKuliah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                (
                    "nama_english",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("kode", models.CharField(max_length=255, unique=True)),
                ("tipe", models.CharField(max_length=255)),
                ("sks", models.IntegerField()),
                ("semester", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ruang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_ruang", models.CharField(max_length=255)),
                ("lokasi", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("nip", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="admin_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="admin_set", to="auth.permission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dosen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nip", models.CharField(max_length=255, unique=True)),
                ("nama", models.CharField(max_length=255)),
                ("mobile_phone", models.CharField(max_length=20)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="dosen_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="dosen_set", to="auth.permission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mahasiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nim", models.CharField(max_length=255, unique=True)),
                ("nama", models.CharField(max_length=255)),
                ("semester", models.IntegerField()),
                ("is_wajah_exist", models.BooleanField(default=False)),
                ("mobile_phone", models.CharField(max_length=20)),
                ("nik", models.CharField(max_length=255, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="mahasiswa_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="mahasiswa_set", to="auth.permission"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Kelas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kelas", models.CharField(max_length=255)),
                ("kode_kelas", models.CharField(max_length=255, unique=True)),
                ("hari", models.CharField(max_length=255)),
                ("jam_mulai", models.TimeField()),
                ("jam_selesai", models.TimeField()),
                ("kapasitas", models.IntegerField()),
                (
                    "mata_kuliah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kelas",
                        to="admin_web.matakuliah",
                    ),
                ),
                (
                    "ruang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kelas",
                        to="admin_web.ruang",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JadwalKelas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("jam_mulai", models.TimeField()),
                ("jam_selesai", models.TimeField()),
                ("status", models.CharField(max_length=255)),
                (
                    "dosen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jadwal_kelas",
                        to="admin_web.dosen",
                    ),
                ),
                (
                    "kelas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jadwal_kelas",
                        to="admin_web.kelas",
                    ),
                ),
                (
                    "mata_kuliah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jadwal_kelas",
                        to="admin_web.matakuliah",
                    ),
                ),
                (
                    "ruang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jadwal_kelas",
                        to="admin_web.ruang",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MataKuliahDosen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.dosen",
                    ),
                ),
                (
                    "mata_kuliah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.matakuliah",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dosen",
            name="mata_kuliah",
            field=models.ManyToManyField(
                related_name="dosens",
                through="admin_web.MataKuliahDosen",
                to="admin_web.matakuliah",
            ),
        ),
        migrations.CreateModel(
            name="MataKuliahMahasiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester_mengambil", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                (
                    "kelas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.kelas",
                    ),
                ),
                (
                    "mahasiswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.mahasiswa",
                    ),
                ),
                (
                    "mata_kuliah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.matakuliah",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mahasiswa",
            name="kelas",
            field=models.ManyToManyField(
                related_name="mahasiswas",
                through="admin_web.MataKuliahMahasiswa",
                to="admin_web.kelas",
            ),
        ),
        migrations.AddField(
            model_name="mahasiswa",
            name="mata_kuliah",
            field=models.ManyToManyField(
                related_name="mahasiswas",
                through="admin_web.MataKuliahMahasiswa",
                to="admin_web.matakuliah",
            ),
        ),
        migrations.CreateModel(
            name="PresensiMahasiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("presensi_oleh", models.CharField(max_length=100)),
                ("tanggal_presensi", models.DateField()),
                (
                    "jadwal_kelas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.jadwalkelas",
                    ),
                ),
                (
                    "kelas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.kelas",
                    ),
                ),
                (
                    "mahasiswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.mahasiswa",
                    ),
                ),
                (
                    "mata_kuliah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_web.matakuliah",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mahasiswa",
            name="jadwal",
            field=models.ManyToManyField(
                related_name="mahasiswas",
                through="admin_web.PresensiMahasiswa",
                to="admin_web.jadwalkelas",
            ),
        ),
    ]
