# Generated by Django 5.1.1 on 2024-10-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("dosen", "Dosen"),
                            ("mahasiswa", "Mahasiswa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="admin",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="dosen",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="dosen",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="dosen",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="mahasiswa",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="mahasiswa",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="mahasiswa",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="presensimahasiswa",
            name="jadwal_kelas",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presensi",
                to="admin_web.jadwalkelas",
            ),
        ),
        migrations.AlterField(
            model_name="presensimahasiswa",
            name="presensi_oleh",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="presensimahasiswa",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hadir", "Hadir"),
                    ("alpha", "Alpha"),
                    ("izin", "Izin"),
                    ("sakit", "Sakit"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="presensimahasiswa",
            name="tanggal_presensi",
            field=models.DateField(blank=True, null=True),
        ),
    ]
