# Generated by Django 5.1.1 on 2024-10-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dosen",
            name="mata_kuliah",
            field=models.ManyToManyField(
                related_name="dosens",
                through="admin_web.MataKuliahDosen",
                to="admin_web.matakuliah",
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="dosen",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="dosen",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="mahasiswa",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="mahasiswa",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
