# Generated by Django 5.1.2 on 2024-10-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_web", "0002_dosen_mata_kuliah_alter_admin_last_login_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_1", models.ImageField(upload_to="face_datasets/")),
                ("image_2", models.ImageField(upload_to="face_datasets/")),
                ("image_3", models.ImageField(upload_to="face_datasets/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mahasiswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_datasets",
                        to="admin_web.mahasiswa",
                    ),
                ),
            ],
        ),
    ]
