# Generated by Django 5.1.1 on 2024-10-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_web",
            "0002_user_remove_admin_groups_remove_admin_is_superuser_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin",
                to="admin_web.user",
            ),
        ),
        migrations.AddField(
            model_name="dosen",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dosen",
                to="admin_web.user",
            ),
        ),
        migrations.AddField(
            model_name="mahasiswa",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mahasiswa",
                to="admin_web.user",
            ),
        ),
    ]
