# Generated by Django 5.1.2 on 2024-10-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_web", "0003_facedataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="WajahMahasiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="wajah_mahasiswa/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mahasiswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wajah",
                        to="admin_web.mahasiswa",
                    ),
                ),
            ],
        ),
    ]
